In [2]:
def get_line(start, end):
    """Bresenham's Line Algorithm
    Produces a list of tuples from start and end
 
    >>> points1 = get_line((0, 0), (3, 4))
    >>> points2 = get_line((3, 4), (0, 0))
    >>> assert(set(points1) == set(points2))
    >>> print points1
    [(0, 0), (1, 1), (1, 2), (2, 3), (3, 4)]
    >>> print points2
    [(3, 4), (2, 3), (1, 2), (1, 1), (0, 0)]
    """
    # Setup initial conditions
    x1, y1 = start
    x2, y2 = end
    dx = x2 - x1
    dy = y2 - y1
 
    # Determine how steep the line is
    is_steep = abs(dy) > abs(dx)
 
    # Rotate line
    if is_steep:
        x1, y1 = y1, x1
        x2, y2 = y2, x2
 
    # Swap start and end points if necessary and store swap state
    swapped = False
    if x1 > x2:
        x1, x2 = x2, x1
        y1, y2 = y2, y1
        swapped = True
 
    # Recalculate differentials
    dx = x2 - x1
    dy = y2 - y1
 
    # Calculate error
    error = int(dx / 2.0)
    ystep = 1 if y1 < y2 else -1
 
    # Iterate over bounding box generating points between start and end
    y = y1
    points = []
    for x in range(x1, x2 + 1):
        coord = (y, x) if is_steep else (x, y)
        points.append(coord)
        error -= abs(dy)
        if error < 0:
            y += ystep
            error += dx
 
    # Reverse the list if the coordinates were swapped
    if swapped:
        points.reverse()
    return points

points1 = get_line((0, 0), (50, 40))
points2 = get_line((50, 40), (0, 0))
assert(set(points1) == set(points2))
print (points1)
print (points2)

[(0, 0), (1, 1), (2, 2), (3, 2), (4, 3), (5, 4), (6, 5), (7, 6), (8, 6), (9, 7), (10, 8), (11, 9), (12, 10), (13, 10), (14, 11), (15, 12), (16, 13), (17, 14), (18, 14), (19, 15), (20, 16), (21, 17), (22, 18), (23, 18), (24, 19), (25, 20), (26, 21), (27, 22), (28, 22), (29, 23), (30, 24), (31, 25), (32, 26), (33, 26), (34, 27), (35, 28), (36, 29), (37, 30), (38, 30), (39, 31), (40, 32), (41, 33), (42, 34), (43, 34), (44, 35), (45, 36), (46, 37), (47, 38), (48, 38), (49, 39), (50, 40)]
[(50, 40), (49, 39), (48, 38), (47, 38), (46, 37), (45, 36), (44, 35), (43, 34), (42, 34), (41, 33), (40, 32), (39, 31), (38, 30), (37, 30), (36, 29), (35, 28), (34, 27), (33, 26), (32, 26), (31, 25), (30, 24), (29, 23), (28, 22), (27, 22), (26, 21), (25, 20), (24, 19), (23, 18), (22, 18), (21, 17), (20, 16), (19, 15), (18, 14), (17, 14), (16, 13), (15, 12), (14, 11), (13, 10), (12, 10), (11, 9), (10, 8), (9, 7), (8, 6), (7, 6), (6, 5), (5, 4), (4, 3), (3, 2), (2, 2), (1, 1), (0, 0)]


Rover transformed vision image is y=160, x=320

In [4]:
from math import sin, cos, radians, pi
def point_pos(x0, y0, d, theta_degrees):
    """   """
    theta_rad = pi/2 - radians(theta_degrees)
    return x0 + d*cos(theta_rad), y0 + d*sin(theta_rad)

top_point = point_pos(160, 160, 150, 15)

print(top_point)

(198.8228567653781, 304.88887394336024)


In [25]:
import numpy as np

driving_mask = np.zeros((20, 20))

driving_mask[:10,:10] = 1 # assign ones to a range of rows and columns
# driving_mask[:,[1,2]] = 1 # select all rows and specific columns
print (driving_mask)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [10]:
import numpy as np

driving_mask = np.zeros((24, 24)) # initialize matrix of zeros 

driving_mask.shape[1], driving_mask.shape[0] # .shape = (rows, col)

H_start_percent = 0 # percent value
H_end_percent = 90 # percent value
V_start_percent = 10 # percent value
V_end_percent = 20 # percent value

def remap_values(value, inMin, inMax, outMin, outMax):
    # Figure out how 'wide' each range is
    inSpan = inMax - inMin
    outSpan = outMax - outMin

    # Convert the left range into a 0-1 range (float)
    valueScaled = float(value - inMin) / float(inSpan)

    # Convert the 0-1 range into a value in the right range.
    return outMin + (valueScaled * outSpan)

H_start_col = int(round(remap_values(H_start_percent, 0, 100, 0, driving_mask.shape[1])))
# print(H_start_col)
H_end_col = int(round(remap_values(H_end_percent, 0, 100, 0, driving_mask.shape[1])))
# print(H_end_col)
V_start_col = int(round(remap_values(V_start_percent, 0, 100, 0, driving_mask.shape[0])))
# print(V_start_col)
V_end_col = int(round(remap_values(V_end_percent, 0, 100, 0, driving_mask.shape[0])))
# print(V_end_col)

driving_mask[V_start_col:V_end_col,H_start_col:H_end_col] = 1 # select range of rows and columns
# driving_mask[:,[1,2]] = 1 # select all rows and specific columns
print (driving_mask)



[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.